project_id = "ajqxtwwbmcphmiftvxho"

[functions.featured-tips]
verify_jwt = false

[functions.symptom-insights]
verify_jwt = false

[functions.community-ai-answer]
verify_jwt = false

[functions.nutrition-goals]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.redeem-promo-code]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
