
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS tutorial_version_completed TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS tutorial_step INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tutorial_hints_seen JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS first_login_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
